version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Set up Python 3.10
          command: |
            sudo apt-get update
            sudo apt-get install python3.10
            sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
            python3 --version

      - run:
          name: Install dependencies
          command: |
            python3 -m pip install --upgrade pip
            pip install numpy flake8
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - run:
          name: Lint with flake8
          command: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The CircleCI editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - run:
          name: Run application
          command: |
            echo "This is the start of the execution"
            python3 warehouse_bot.py
            echo "The execution has ended"
